-- ═══════════════════════════════════════════════════════════════════════
-- Oprava: sessions a sm2_cards se nikdy nezapsaly (audit 2026-09-19)
--
-- PŘÍČINA: sessions.user_id a sm2_cards.user_id mají cizí klíč na public.users(id),
-- což je prázdná pozůstalá tabulka. Skuteční uživatelé jsou v auth.users, takže
-- každý INSERT/UPSERT porušil cizí klíč a tiše selhal (Supabase JS při chybě
-- nevyhazuje výjimku a kód kontrolu `error` nedělá). Kvůli tomu jsou obě tabulky
-- prázdné a z nich čtou rodičovský dashboard, týdenní report, denní push a admin.
--
-- SPUSTIT RUČNĚ v Supabase SQL Editoru (projekt pkjckadolkoosoblagvr) POTÉ,
-- co zkontroluješ výstup diagnostického dotazu. Tabulky jsou prázdné, takže
-- změna nemůže přijít o data. Skript je idempotentní.
-- ═══════════════════════════════════════════════════════════════════════

-- 1) Zahodit cizí klíče na public.users (jméno klíče neznáme, hledáme podle cíle)
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conrelid::regclass AS tbl, conname
    FROM pg_constraint
    WHERE contype = 'f'
      AND confrelid = 'public.users'::regclass
      AND conrelid IN ('public.sessions'::regclass, 'public.sm2_cards'::regclass)
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname);
    RAISE NOTICE 'Zahozen cizí klíč % na %', r.conname, r.tbl;
  END LOOP;
END $$;

-- 2) Nové cizí klíče na auth.users (smazání uživatele smaže i jeho historii)
ALTER TABLE public.sessions  DROP CONSTRAINT IF EXISTS sessions_user_id_fkey;
ALTER TABLE public.sm2_cards DROP CONSTRAINT IF EXISTS sm2_cards_user_id_fkey;
ALTER TABLE public.sessions  ADD CONSTRAINT sessions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.sm2_cards ADD CONSTRAINT sm2_cards_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- 3) upsert v remoteSaveSM2Card (onConflict: "user_id,example_id") vyžaduje unikátní klíč
CREATE UNIQUE INDEX IF NOT EXISTS sm2_cards_user_example_uidx
  ON public.sm2_cards (user_id, example_id);

-- 4) Sloupec id musí mít automatickou hodnotu, jinak INSERT bez id selže
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sessions', 'sm2_cards'] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = t AND column_name = 'id'
        AND column_default IS NULL AND is_identity = 'NO'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
      RAISE NOTICE 'Přidána identita na %.id', t;
    END IF;
  END LOOP;
END $$;

-- 5) Kontrola: oba cizí klíče teď míří na auth.users
SELECT conrelid::regclass AS tabulka, conname, confrelid::regclass AS ukazuje_na
FROM pg_constraint
WHERE contype = 'f' AND conrelid IN ('public.sessions'::regclass, 'public.sm2_cards'::regclass);
