-- ═══════════════════════════════════════════════════════════════════════
-- Podmínky pro opravené trasy /api/push-subscribe a /api/referral (audit 2026-09-19)
--
-- Obě trasy dřív zapisovaly anonymním klientem, který RLS potichu odmítala
-- (push_subscriptions i referrals mají 0 řádků). Nový kód zapisuje přes
-- service-role klient a potřebuje:
--   • unikátní klíč push_subscriptions(endpoint) pro upsert (onConflict: "endpoint"),
--   • jedno doporučení na nového uživatele (referrals.referred_user_id),
--   • automatické id u obou tabulek.
-- Tabulky jsou prázdné, změna nemůže přijít o data. SPUSTIT RUČNĚ v SQL Editoru.
-- Idempotentní.
-- ═══════════════════════════════════════════════════════════════════════

CREATE UNIQUE INDEX IF NOT EXISTS push_subscriptions_endpoint_uidx
  ON public.push_subscriptions (endpoint);

CREATE UNIQUE INDEX IF NOT EXISTS referrals_referred_user_uidx
  ON public.referrals (referred_user_id);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['push_subscriptions', 'referrals'] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = t AND column_name = 'id'
        AND column_default IS NULL AND is_identity = 'NO'
        AND data_type IN ('bigint', 'integer')
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
      RAISE NOTICE 'Přidána identita na %.id', t;
    END IF;
  END LOOP;
END $$;

-- Kontrola
SELECT indexname, tablename FROM pg_indexes
WHERE schemaname = 'public' AND tablename IN ('push_subscriptions', 'referrals');
